---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dz77qxrgv7cy/public_html
    - tar --exclude='.git' --exclude='.cpanel.yml' --exclude='.gitignore' -cf - . | (cd $DEPLOYPATH && tar -xf -)
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
